In [27]:
import numpy as np 
import torch 

In [55]:
## 绝对坐标 -1 到 1
idx = [0, 2]
xx = np.arange(-1, 1.5, 0.5)[idx]
yy = np.arange(-1, 1.5, 0.5)[idx]
v = np.arange(1, 26).reshape(5,5)[None,None]
print(v)
grid = np.meshgrid(*[xx, yy])
grid = [g[:,:,None] for g in grid]
grid = np.concatenate(grid, axis=-1)
grid = grid[None]
grid = torch.from_numpy(grid)

u = torch.nn.functional.grid_sample(torch.from_numpy(v).float(), grid.float(), align_corners=True)
print(u)

[[[[ 1  2  3  4  5]
   [ 6  7  8  9 10]
   [11 12 13 14 15]
   [16 17 18 19 20]
   [21 22 23 24 25]]]]
tensor([[[[ 1.,  3.],
          [11., 13.]]]])


In [54]:
u

tensor([[[[ 1.,  2.,  3.,  4.,  5.],
          [ 6.,  7.,  8.,  9., 10.],
          [11., 12., 13., 14., 15.],
          [16., 17., 18., 19., 20.],
          [21., 22., 23., 24., 25.]]]])

In [52]:
grid.shape

torch.Size([1, 8, 8, 2])

In [13]:
gg * d

array([[[[1. , 4. ],
         [1.2, 4. ],
         [1.4, 4. ],
         [1.6, 4. ],
         [1.8, 4. ]],

        [[1. , 4.4],
         [1.2, 4.4],
         [1.4, 4.4],
         [1.6, 4.4],
         [1.8, 4.4]],

        [[1. , 4.8],
         [1.2, 4.8],
         [1.4, 4.8],
         [1.6, 4.8],
         [1.8, 4.8]],

        [[1. , 5.2],
         [1.2, 5.2],
         [1.4, 5.2],
         [1.6, 5.2],
         [1.8, 5.2]],

        [[1. , 5.6],
         [1.2, 5.6],
         [1.4, 5.6],
         [1.6, 5.6],
         [1.8, 5.6]]]])